replicaCount: 1

image: 
  repository: matomo
  tag: '3.13.6'
  imagePullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80

resources: {}

trustedHostsCheck: 0

db:
  port: '3306'
  host: '127.0.0.1'
  tablesPrefix: 'matomo_'


dbProxy:
  instances: "-instances=selfkey2:asia-east2:matomo=tcp:3306"

gcePersistentDisk:
  pdName: matomo-nfs-disk
  fsType: ext4
  size: 20Gi

dbServiceAccount: matomo-sql

ingressDomain: false

tlsSecret: false