apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "matomo.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "matomo.name" . }}
    helm.sh/chart: {{ include "matomo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  schedule: "0 */1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: {{ include "matomo.fullname" . }}-nfs
            persistentVolumeClaim:
              claimName: {{ include "matomo.fullname" . }}-nfs
          {{- if .Values.dbServiceAccount }}
          serviceAccountName: {{ .Values.dbServiceAccount }}
          {{- end }}
          containers:
          - name: {{ .Chart.Name }}-app
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            volumeMounts:
              - name: {{ include "matomo.fullname" . }}-nfs
                mountPath: /var/www/html
            command:
              - /bin/bash
              - -c
              - "/usr/local/bin/php /var/www/html/console core:archive --url={{ .Values.websiteUrl }}"
          - name: cloud-sql-proxy
            # It is recommended to use the latest version of the Cloud SQL proxy
            # Make sure to update on a regular schedule!
            image: gcr.io/cloudsql-docker/gce-proxy:1.17
            command:
              - "/cloud_sql_proxy"

              # If connecting from a VPC-native GKE cluster, you can use the
              # following flag to have the proxy connect over private IP
              # - "-ip_address_types=PRIVATE"

              # Replace DB_PORT with the port the proxy should listen on
              # Defaults: MySQL: 3306, Postgres: 5432, SQLServer: 1433
              - !!string {{ .Values.dbProxy.instances}}
            securityContext:
              # The default Cloud SQL proxy image is based on distroless, which
              # runs as the "nonroot" user (uid: 65534) by default.
              runAsNonRoot: true
              runAsUser: 65532
              runAsGroup: 65532
          restartPolicy: OnFailure