{{- $fullName := include "matomo.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "matomo.name" . }}
    helm.sh/chart: {{ include "matomo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    {{- if .Values.ingressDomain }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingressDomain }}
    {{- end }}
spec:
  {{- if .Values.tlsSecret }}
  tls: 
  - hosts:
      - {{ .Values.ingressDomain }}
    secretName: {{ .Values.tlsSecret }}
  {{- end }}
  
  {{- if .Values.ingressDomain }}
  rules:
  - host: {{ .Values.ingressDomain }} 
    http:
      paths:
      - backend:
          serviceName: {{ $fullName }}
          servicePort: {{ $servicePort }}
  {{- else }}
  backend:
    serviceName: {{ $fullName }}
    servicePort: {{ $servicePort }}
  {{- end }}