{{- $fullName := include "matomo.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "matomo.name" . }}
    helm.sh/chart: {{ include "matomo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    {{- if .Values.ingressDomain }}
      ingressDomain: {{ .Values.ingressDomain }}
    {{- end }}
spec:
  backend:
    serviceName: {{ $fullName }}
    servicePort: {{ $servicePort }}

external-dns.alpha.kubernetes.io/hostname: