apiVersion: v1
kind: Service
metadata:
  name: {{ include "matomo.fullname" . }}-nfs
  labels:
    app.kubernetes.io/name: {{ include "matomo.name" . }}-nfs
    helm.sh/chart: {{ include "matomo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

spec:
  # clusterIP: 10.3.240.20
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    app.kubernetes.io/name: {{ include "matomo.name" . }}-nfs